name: e2e and unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
      - run: npm ci
      - run: npm run test:unit

  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Install Dependencies
        run: npm ci

      - name: Build app
        run: npm run build
        env:
          MONGODB_URI: mongodb://localhost:27017/test_db
          NEXTAUTH_SECRET: '${{ secrets.NEXTAUTH_SECRET }}'
          NEXTAUTH_URL: http://localhost:3000

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build App
        run: npm run build
        env:
          MONGODB_URI: mongodb://localhost:27017/test_db
          NEXTAUTH_SECRET: '${{ secrets.NEXTAUTH_SECRET }}'
          NEXTAUTH_URL: http://localhost:3000

      - name: Run Playwright Tests
        run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        env:
          MONGODB_URI: mongodb://localhost:27017/test_db
          NEXTAUTH_SECRET: '${{ secrets.NEXTAUTH_SECRET }}'
          NEXTAUTH_URL: http://localhost:3000

      - name: Upload Blob Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1

  merge-reports:
    if: ${{ !cancelled() }}
    needs: [playwright-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
      - run: npm ci
      - name: Download all blobs
        uses: actions/download-artifact@v4
        with:
          path: all-blobs
          pattern: blob-report-*
          merge-multiple: true
      - name: Merge into HTML
        run: npx playwright merge-reports --reporter html ./all-blobs
      - name: Upload Merged Report
        uses: actions/upload-artifact@v4
        with:
          name: final-playwright-report
          path: playwright-report/
          retention-days: 7
