name: e2e and unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - run: npm ci
      - run: npm run test:unit

  wait-for-deployment:
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercel.outputs.url }}
    steps:
      - name: Wait for Vercel
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.2
        id: waitForVercel
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 600
  e2e-auth-setup:
    needs: [wait-for-deployment]
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.58.0-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - run: npm ci

      - name: Generate Auth Session
        run: npx playwright test auth.setup.ts
        env:
          HOME: /root
          BASE_URL: ${{ needs.wait-for-deployment.outputs.preview_url }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          MONGOTESTDB_URI: ${{ secrets.MONGOTESTDB_URI }}

      - name: Upload Session Artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-session
          path: e2e/utils/user.json
          retention-days: 1

  playwright-e2e:
    needs: [wait-for-deployment, e2e-auth-setup]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    container:
      image: mcr.microsoft.com/playwright:v1.58.0-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - run: npm ci

      - name: Download Session Artifact
        uses: actions/download-artifact@v4
        with:
          name: playwright-session
          path: e2e/utils/

      - name: Run Sharded Tests
        run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        env:
          HOME: /root
          BASE_URL: ${{ needs.wait-for-deployment.outputs.preview_url }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          MONGOTESTDB_URI: ${{ secrets.MONGOTESTDB_URI }}
          CI: true

      - name: Upload Blob Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: all-blob-reports-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1

  merge-reports:
    if: always()
    needs: [playwright-e2e]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
      - run: npm install @playwright/test
      - name: Download all blobs
        uses: actions/download-artifact@v4
        with:
          path: all-blobs
          pattern: all-blob-reports-*
          merge-multiple: true
      - name: Generate Final Report
        run: npx playwright merge-reports --reporter html ./all-blobs
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: final-playwright-report
          path: playwright-report/
