name: e2e and unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - run: npm ci
      - run: npm run test:unit

  # 2. BUILD ONCE (Shared by all Shards)
  build-for-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - run: npm ci
      - name: Build Next.js
        run: npm run build
        env:
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: '${{ secrets.NEXTAUTH_SECRET }}'
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next
          retention-days: 1

  playwright-e2e:
    needs: [build-for-e2e]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]

    services:
      mongodb:
        image: mongo:6.0
        ports: ['27017:27017']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: .next

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        env:
          MONGOTESTDB_URI: mongodb://localhost:27017/test_db
          NEXTAUTH_SECRET: '${{ secrets.NEXTAUTH_SECRET }}'
          NEXTAUTH_URL: http://localhost:3000
          PORT: 3000
          NODE_ENV: test

      - name: Upload Blobs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1

  merge-reports:
    if: always()
    needs: [playwright-e2e]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
      - run: npm ci
      - name: Download all blobs
        uses: actions/download-artifact@v4
        with:
          path: all-blobs
          pattern: blob-report-*
          merge-multiple: true
      - name: Generate Final Report
        run: npx playwright merge-reports --reporter html ./all-blobs
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: final-report
          path: playwright-report/
